Feature/back button my account
vtex-apps/wish-list pull request #91
Opened 2022-01-19 13:03 UTC by arturmagalhaesjr

2022-01-26 18:54 UTC, polishq requested changes
A few requests:

- Please remove any commented code lines and console.log statements.
- I'm seeing a few lint warnings/errors in various files. They're unrelated to your changes but they should be cleaned up regardless. For example in `react/ProductSummaryWishlist.tsx` line 120 there's a "prefer early return" warning. 
- Please update the `vtex.render-runtime` manifest dependency to 8.x
- Your linter should be auto-formatting the changelog (headers should have line breaks before and after)
- Please rename `react/typings/vtex.my-account-commons.d copy.ts` to `react/typings/vtex.my-account-commons.d.ts`

2022-01-27 17:58 UTC, arturmagalhaesjr reviewed
done

2022-01-27 21:02 UTC, polishq requested changes

2022-01-27 21:02 UTC, polishq commented on react/AddProductBtn.tsx
> +  // } else if (
Please remove this commented code

2022-01-27 21:02 UTC, polishq commented on react/AddProductBtn.tsx
> +  // } else if (
(and the following commented lines)

2022-01-28 14:22 UTC, arturmagalhaesjr reviewed
done

2022-01-28 14:26 UTC, polishq approved these changes

2022-01-28 17:10 UTC, merged